spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/starwars?createDatabaseIfNotExist=true&serverTimezone=UTC
    password: mysql123
  jpa:
    hibernate:
      ddl-auto: update
